module load oneapi/eng-compiler/2024.07.30.002
module load cmake/3.27.9
module load swig
module load doxygen
 
export SWIG_EXECUTABLE=$(command -v swig)
export OPENMM_CC=$(which icx)
export OPENMM_CXX=$(which icpx)
 
#MAKE SURE PATH FOR OPENCL_INC AND OPENCL_LIB IS CORRECT FOR YOUR COMPILER!
#NOTE NOTE NOTE - SPECIFICALLY CUSTOMIZED FOR AURORA FOR 2024.1 COMPILER (module load oneapi/eng-compiler/2024.04.15.002)
#IF YOU CHANGE SYSTEMS OR MODULES/COMPILERS, THESE PATHS NEED TO BE CHANGED
#(IF YOU CAN HAVE A MORE ROBUST METHOD FOR HEADERS/LIBRARIES PATHS, PLEASE LEAVE A COMMENT BELOW)
export OPENCL_BASE=$(command dirname -- "${OPENMM_CC}")
export OPENCL_BASE=$(cd "${OPENCL_BASE}/../../../" && command pwd -P)
export OPENCL_INC="${OPENCL_BASE}/compiler/eng-20240629/include/sycl"
export OPENCL_LIB="${OPENCL_BASE}/compiler/eng-20240629/lib/libOpenCL.so"
 
mkdir build
 
cd build
 
cmake ..  -DCMAKE_BUILD_TYPE=Release -DOPENMM_BUILD_OPENCL_LIB=ON -DOPENMM_BUILD_CPU_LIB=ON -DOPENMM_BUILD_PME_PLUGIN=ON  -DOPENMM_BUILD_AMOEBA_PLUGIN=ON  -DOPENMM_BUILD_PYTHON_WRAPPERS=ON -DOPENMM_BUILD_C_AND_FORTRAN_WRAPPERS=OFF -DOPENMM_BUILD_EXAMPLES=ON  -DCMAKE_C_COMPILER=${OPENMM_CC} -DCMAKE_CXX_COMPILER=${OPENMM_CXX} -DOPENCL_INCLUDE_DIR=${OPENCL_INC} -DOPENCL_LIBRARY=${OPENCL_LIB} -DSWIG_EXECUTABLE=${SWIG_EXECUTABLE} -DCMAKE_INSTALL_PREFIX="./install"
 
VERBOSE=1 make -j16
 
make install
